# IMPORTAÇÃO DOS DADOS

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Doutorado/machinelearning/bdinfameprocessado.csv',
                    sep=',', encoding='iso-8859-1')

In [4]:
df

ASC  concentration codigo   P0   P1   P2   P3   P4   P5    P6  ...  \
0    158767         3500.0      A  162  421  730  752  817  933  1056  ...   
1    158573         3500.0      A  198  406  705  748  823  937  1068  ...   
2    157727         3500.0      A  200  191  446  714  827  938  1070  ...   
3    158378         3500.0      A  197  379  670  749  824  941  1072  ...   
4    158395         3500.0      A  193  381  680  747  828  944  1075  ...   
..      ...            ...    ...  ...  ...  ...  ...  ...  ...   ...  ...   
215    3396            6.5      J   42   55   66   43   27   26    25  ...   
216    3344            6.5      J   41   47   57   38   27   26    24  ...   
217    3179            6.5      J   41   21   21   18   28   26    24  ...   
218    3398            6.5      J   36   61   77   50   29   28    29  ...   
219    3381            6.5      J   38   59   74   49   29   27    28  ...   

     P50  P51  P52  P53  P54  P55  P56  P57  P58  P59  
0    626  568  509  455  418  373  325  292  253  221  
1    626  565  505  449  413  374  332  297  258  227  
2    627  566  505  455  418  372  325  291  252  219  
3    624  567  506  453  416  373  329  295  256  221  
4    616  562  509  456  420  376  329  291  250  216  
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
215   15   17   14   12   15   16   21   30   33   36  
216   15   18   14   12   15   16   20   30   33   37  
217   16   17   14   13   17   16   21   30   33   38  
218   21   17   16   17   13   17   22   23   31   38  
219   21   17   17   17   12   16   22   24   32   37  

[220 rows x 63 columns]

In [5]:
df.shape

(220, 63)

# REGRESSÃO COM RANDOM FOREST

In [6]:
independente_rf = df.iloc[:, 3:].values
independente_rf

array([[162, 421, 730, ..., 292, 253, 221],
       [198, 406, 705, ..., 297, 258, 227],
       [200, 191, 446, ..., 291, 252, 219],
       ...,
       [ 41,  21,  21, ...,  30,  33,  38],
       [ 36,  61,  77, ...,  23,  31,  38],
       [ 38,  59,  74, ...,  24,  32,  37]])

In [7]:
dependente_rf = df.iloc[:, 1].values
dependente_rf

array([3500. , 3500. , 3500. , 3500. , 3500. , 3500. , 3500. , 3500. ,
       3500. , 3500. , 3500. , 3500. , 3500. , 3500. , 3500. , 3500. ,
       3500. , 3500. , 3500. , 3500. , 3500. , 3500. , 3500. , 3500. ,
       3500. , 1750. , 1750. , 1750. , 1750. , 1750. , 1750. , 1750. ,
       1750. , 1750. , 1750. , 1750. , 1750. , 1750. , 1750. , 1750. ,
       1750. , 1750. , 1750. , 1750. , 1750. , 1750. , 1750. , 1750. ,
       1750. , 1750. ,  875. ,  875. ,  875. ,  875. ,  875. ,  875. ,
        875. ,  875. ,  875. ,  875. ,  875. ,  875. ,  875. ,  875. ,
        875. ,  875. ,  875. ,  875. ,  875. ,  875. ,  875. ,  875. ,
        875. ,  875. ,  875. ,  437. ,  437. ,  437. ,  437. ,  437. ,
        437. ,  437. ,  437. ,  437. ,  437. ,  437. ,  437. ,  437. ,
        437. ,  437. ,  437. ,  437. ,  437. ,  437. ,  437. ,  437. ,
        437. ,  437. ,  437. ,  437. ,  218. ,  218. ,  218. ,  218. ,
        218. ,  218. ,  218. ,  218. ,  218. ,  218. ,  218. ,  218. ,
      

In [8]:
independente_rf.shape

(220, 60)

In [9]:
dependente_rf.shape

(220,)

### Modelo

In [10]:
from sklearn.model_selection import train_test_split
x_treino, x_teste, y_treino, y_teste = train_test_split(independente_rf, dependente_rf, test_size = 0.3, random_state = 0)

In [11]:
x_treino.shape, y_treino.shape

((154, 60), (154,))

In [12]:
x_teste.shape, y_teste.shape

((66, 60), (66,))

In [13]:
from sklearn.ensemble import RandomForestRegressor

In [14]:
random = RandomForestRegressor(n_estimators=60, criterion='squared_error', max_depth=4, random_state = 10)
random.fit(x_treino, y_treino)

RandomForestRegressor(max_depth=4, n_estimators=60, random_state=10)

In [15]:
random.score(x_treino, y_treino)

0.9999022472232602

In [16]:
random.score(x_teste, y_teste)

0.9999022954527098

In [17]:
previsoes_teste = random.predict(x_teste)
previsoes_teste

array([  32.91524347,  875.        ,  875.        ,   32.91524347,
         32.91524347,   99.9469834 ,  875.        ,   32.91524347,
         32.91524347,   99.9469834 ,   99.9469834 , 3500.        ,
        437.        ,   32.91524347,   32.91524347,   32.91524347,
         32.91524347,  437.        ,  216.18333333,  433.35      ,
        875.        , 3500.        ,   32.91524347,  875.        ,
       1750.        ,   99.9469834 ,  218.        ,  875.        ,
       3500.        , 3500.        ,   32.91524347, 3500.        ,
         99.9469834 , 3500.        ,  214.36666667,   32.91524347,
         99.9469834 ,   99.9469834 ,   32.91524347,   32.91524347,
        875.        , 1750.        ,  437.        ,   32.91524347,
         32.91524347,   32.91524347,   32.91524347,   32.91524347,
       3500.        ,   99.9469834 ,   39.24218792,   99.9469834 ,
       3500.        ,   32.91524347, 1750.        ,   32.91524347,
       3500.        ,   32.91524347,  437.        , 1750.     

In [18]:
random.n_features_in_

60

### Métricas

In [19]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [20]:
# Erro médio Absoluto (MAE)
mean_absolute_error(previsoes_teste, y_teste)

7.572058445725924

In [21]:
# Erro médio Quadratico (MSE)
mean_squared_error(previsoes_teste, y_teste)

134.7876633102908

In [22]:
# Raiz do Erro médio Quadratico (RMSE)
np.sqrt(mean_squared_error(previsoes_teste, y_teste))

np.float64(11.609808926519454)

### Prevendo Valores Separadamente

In [23]:
# Prevendo a concentração de 1750ppm
random.predict(np.array(df.iloc[25, 3:]).reshape(1,-1))

array([1750.])

In [24]:
# Prevendo a concentração de 875ppm
random.predict(np.array(df.iloc[50, 3:]).reshape(1,-1))

array([875.])

In [25]:
# Prevendo a concentração de 437ppm
random.predict(np.array(df.iloc[75, 3:]).reshape(1,-1))

array([433.35])

In [26]:
#Prevendo concentrações de outros BD: (1750ppm, Dia 07/10/25 - EXP9)
exp1 = [119,177,324,459,546,632,725,825,930,1032,1132,1216,1260,1255,1187,1037,799,487,132,325,750,1178,1583,1946,2240,2462,2603,2653,2615,2496,2291,2009,1669,1280,843,441,93,289,564,766,893,953,962,931,876,810,733,658,590,520,459,410,361,321,291,259,234,211,181,160]
random.predict(np.array(exp1).reshape(1,-1))


array([1808.33333333])

In [27]:
#Prevendo concentrações de outros BD: (1750ppm, Dia 10/09/25 - EXP9)
exp2 = [126,169,316,488,597,682,775,877,981,1081,1172,1238,1265,1229,1119,932,662,318,128,537,977,1399,1787,2121,2388,2577,2680,2694,2615,2451,2205,1885,1508,1100,679,276,134,431,677,848,944,978,965,919,852,775,699,621,546,482,423,372,331,294,262,239,215,191,172,155]
random.predict(np.array(exp2).reshape(1,-1))

array([1750.])

In [28]:
#Prevendo concentrações de outros BD: (437ppm, Dia 10/09/25 - EXP13)
exp3=[72,81,120,170,207,233,262,293,324,354,382,401,404,390,355,292,204,96,45,175,310,438,554,651,726,780,807,805,775,719,639,537,421,291,158,33,91,188,263,314,343,350,343,324,298,267,232,198,167,139,116,99,85,77,72,67,67,69,69,74]
random.predict(np.array(exp3).reshape(1,-1))

array([466.2])

In [29]:
#Prevendo concentrações de outros BD: Vácuo
eixoyvacuo = [15,23,42,30,30,32,33,35,38,40,39,41,43,38,35,36,31,25,24,22,14,12,15,13,13,20,21,21,26,27,24,27,27,25,26,26,25,26,27,32,38,40,44,47,43,46,53,54,58,61,55,54,49,39,37,33,22,19,16,12]
random.predict(np.array(eixoyvacuo).reshape(1,-1))

array([44.86033379])

In [30]:
#Prevendo concentrações de outros BD: Nitrogênio
eixoynitro = [72,81,75,42,23,24,26,28,33,37,38,41,44,41,36,37,36,30,28,27,21,17,20,17,12,14,12,8,8,9,9,10,14,18,24,30,33,39,45,51,56,58,59,63,63,63,66,58,50,45,32,24,26,23,23,26,24,26,30,26]
random.predict(np.array(eixoynitro).reshape(1,-1))

array([42.4018818])

In [31]:
# Prevendo uma linha do dataframe x_teste

random.predict(x_teste[0].reshape(1,-1))

array([32.91524347])

In [32]:
# Prevendo uma linha do df, com 218 ppm
random.predict(np.array(df.iloc[100, 3:]).reshape(1,-1))

array([221.65])

In [33]:
# Prevendo uma linha do df, com 109 ppm
random.predict(np.array(df.iloc[125, 3:]).reshape(1,-1))

array([99.9469834])

In [34]:
# Prevendo uma linha do df, com 54 ppm
random.predict(np.array(df.iloc[150, 3:]).reshape(1,-1))

array([32.91524347])

In [35]:
# Prevendo uma linha do df, com 27 ppm
random.predict(np.array(df.iloc[175, 3:]).reshape(1,-1))

array([32.91524347])

In [36]:
# Prevendo uma linha do df, com 13 ppm
random.predict(np.array(df.iloc[200, 3:]).reshape(1,-1))

array([39.24218792])

Com este modelo, o algoritmo quantifica as curvas até 54ppm. Após isso tudo é mostrado com o mesmo valor!

### Conversão para C

In [37]:
pip install m2cgen

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.2/92.2 kB 3.1 MB/s eta 0:00:00


In [38]:
import m2cgen as m2c

In [39]:
#Gera código C equivalente
code = m2c.export_to_c(random)

# Salva o código
with open("randomforest.c", "w") as f:
    f.write(code)

In [40]:
# Teste em C no próprio colab

main_code = r"""
#include <stdio.h>
#include "randomforest.c"

int main() {
    double input[60] = {119,177,324,459,546,632,725,825,930,1032,1132,1216,1260,1255,1187,1037,799,
                    487,132,325,750,1178,1583,1946,2240,2462,2603,2653,2615,2496,2291,2009,1669,1280,
                    843,441,93,289,564,766,893,953,962,931,876,810,733,658,590,520,459,410,361,321,291,
                    259,234,211,181,160};

    double result = score(input);
    printf("Saída no C: %f\n", result);
    return 0;
}
"""

with open("rf.c", "w") as f:
    f.write(main_code)

In [41]:
!gcc rf.c -o rf
!./rf

Saída no C: 1808.333333


In [42]:
#Prevendo concentrações de outros BD: (1750ppm, Dia 07/10/25 - EXP9)
exp1 = [119,177,324,459,546,632,725,825,930,1032,1132,1216,1260,1255,1187,1037,799,487,132,325,750,1178,1583,1946,2240,2462,2603,2653,2615,2496,2291,2009,1669,1280,843,441,93,289,564,766,893,953,962,931,876,810,733,658,590,520,459,410,361,321,291,259,234,211,181,160]
print(f'Saída no Python: {random.predict(np.array(exp1).reshape(1,-1))}')


Saída no Python: [1808.33333333]


In [43]:
#Saída no STM32: 1808.3334